### ISSUE TITLE
Quiz Formatting

### ISSUE THREAD

**Issue by ncaudill27** [learn-co-curriculum/programming-univbasics-nds-quiz#3]
NDS Quiz is not allowing for selection of answers to questions. Instead displaying the answers for the quiz. I tried to refresh and no luck.

It looks like this =>
?: Which NDS does the following code represent?

    [ { :name => "James" }, { :name => "LeBron" }, { :name => "O'Shea" } ]

( ) Array of Arrays
(X) Array of Hashes
( ) Hash of Arrays
( ) Hash of Hashes

**Comment by ncaudill27** [comment]
So I'm not really sure how the file works, but I did notice something in this quiz compared to others.
When it drops the ``` to open code blocks in the raw README. On this file they show ```ruby. Maybe it's that?

**Comment by sgharms** [comment]
We found a bug in our renderer. It has been fixed. We apologize for any inconvenience.
