### ISSUE TITLE
Unable to submit quiz answers

### ISSUE THREAD

**Issue by ebonyash15** [learn-co-curriculum/programming-univbasics-nds-quiz#4]
The Recognizing Nested Data Structures Quiz has loaded without buttons for me to click on to select an answer. Instead the answer options are listed and the correct answers are marked with an "(x)" in front of them. I am unable to alieviate the issue by closing the tab and reopening but it did remove my option to Ask a Question -- which normally is disabled through quizes -- when I closed and reloaded the page.

**Comment by ChrstphGrnr** [comment]
This is still the case and I have the same issue when attempting to do the Quiz!

**Comment by ebonyash15** [comment]
I have run into this on future quizzes as well.

Thank you,

Ebony

**Comment by sgharms** [comment]
We found a bug in our renderer. It has been fixed. We apologize for any inconvenience.

**Comment by ebonyash15** [comment]
Thank you very much!
