### ISSUE TITLE
Lab broken and some answers not showing correctly

### ISSUE THREAD

**Issue by ChrstphGrnr** [learn-co-curriculum/programming-univbasics-nds-quiz#5]
Not only is this lab broken, as in, the quiz can't be run, the static page seems to point to false answers in some of the questions. 

?: Given the following NDS, what does the following code produce?

```
trios = [
  ["Geddy", "Alex", "Neal"],
  ["Raekwon", "ODB", "The RZA"],
  ["The Micke", "Joltin' Joe", "Say Hey Kid"]
 
  trios[0][5] = "John"
  trios[0] #=>  ???
]
( ) ["Geddy", "Alex", "Neal", "John"]
( ) ["Geddy", "Alex", "Neal", nil, nil, "John"]
(X) ["Geddy", "Alex", "Neal", nil, "John"]
( ) ["Geddy", "Alex", "Neal", "John", nil]

```
This should obviously be a different answer!

**Comment by sgharms** [comment]
We found a bug in our renderer. It has been fixed. We apologize for any inconvenience.
