### ISSUE TITLE
question 9

### ISSUE THREAD

**Issue by ebaaali** [learn-co-curriculum/programming-univbasics-nds-quiz#6]
trios[0][5] = "John"
  trios[0] #=>  ?? Choose option below ??

says the right answer is ["Geddy", "Alex", "Neal", nil, "John"]

instead of ["Geddy", "Alex", "Neal", nil, nil, "John"]

why is "John" in index 4 rather than 5? Am I missing something?

**Comment by sgharms** [comment]
Nope! You're right. We're wrong. Fixed!
