### ISSUE TITLE
Recognizing Nested Data Structures Quiz. Given the following NDS, what does the following code produce? is wrong

### ISSUE THREAD

**Issue by nicksolony** [learn-co-curriculum/programming-univbasics-nds-quiz#7]
Given the following NDS, what does the following code produce?

trios = [
  ["Geddy", "Alex", "Neal"],
  ["Raekwon", "ODB", "The RZA"],
  ["The Micke", "Joltin' Joe", "Say Hey Kid"]
]
  trios[0][5] = "John"
  trios[0] #=>  ?? Choose option below ??

see question above:

I answered:
["Geddy", "Alex", "Neal", nil, nil, "John"]

but it highlighted it with red and showed correct answer as "["Geddy", "Alex", "Neal", nil, "John"]
"

I run a test in sandbox and my answer is correct, please fix

**Comment by sgharms** [comment]
You're right! Fixed.
